// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vubmiuojqsycaqlbjekz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1Ym1pdW9qcXN5Y2FxbGJqZWt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODU4MzIsImV4cCI6MjA2OTQ2MTgzMn0.3LqGuMU8oRONP7_L-q3g85dUD_mgsXWmAcoljoR8IK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});